---
- name: Find out OS release
  shell: . /etc/os-release  && echo $ID
  register: osrelease

- name: Add yum repository for AdoptJDK
  yum_repository:
    baseurl: "http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/{{ osrelease }}/$releasever/$basearch"
    enabled: yes
    gpgcheck: yes
    gpgkey: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    name: adoptjdk_role
    description: AdoptJDK Java packages
    state: "{{ adoptjdk_state }}"

- name: Install AdoptJDK package
  yum:
    name: "{{ adoptjdk_package }}"
    state: "{{ adoptjdk_state }}"
    update_cache: yes
